config/routes.rb
Ievent::Application.routes.draw do

  devise_for :users

  resources :events do
    collection do
      get "list"
    end
  end

  root :to => 'events#index'

end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :user

  @@notify_type = %w(Once Daily Weekly Monthly Yearly)

  scope :active, where('STRFTIME("%Y-%m-%d", [from]) <= ?', DateTime.now.strftime("%Y-%m-%d"))
  scope :allDay, lambda { |_allDay| where(:allDay => _allDay) }
  scope :repeat, lambda { |_repeat| where("repeat = ?", _repeat) }
  scope :once, lambda { |allDay_|
    if allDay_
      repeat("once").allDay(allDay_).where('STRFTIME("%Y-%m-%d", [from]) = ?', DateTime.now.strftime("%Y-%m-%d"))
    else
      repeat("once").allDay(allDay_).where('STRFTIME("%Y-%m-%d %H:%M", [from]) = ?', DateTime.now.strftime("%Y-%m-%d %H:%M"))
    end
  }

  scope :daily, lambda { |allDay_|
    if allDay_
      active.repeat("daily").allDay(allDay_)
    else
      active.repeat("daily").allDay(allDay_).where('STRFTIME("%H:%M", [from]) = ?', DateTime.now.strftime("%H:%M"))
    end
  }

  scope :weekly, lambda { |allDay_|
    if allDay_
      active.repeat("weekly").allDay(allDay_).where('STRFTIME("%w", [from]) = ?', DateTime.now.strftime("%w"))
    else
      active.repeat("weekly").allDay(allDay_).where('STRFTIME("%w %H:%M", [from]) = ?', DateTime.now.strftime("%w %H:%M"))
    end
  }

  scope :monthly, lambda { |allDay_|
    if allDay_
      active.repeat("monthly").allDay(allDay_).where('STRFTIME("%d", [from]) = ?', DateTime.now.strftime("%d"))
    else
      active.repeat("monthly").allDay(allDay_).where('STRFTIME("%d %H:%M", [from]) = ?', DateTime.now.strftime("%d %H:%M"))
    end
  }

  scope :yearly, lambda { |allDay_|
    if allDay_
      active.repeat("yearly").allDay(allDay_).where('STRFTIME("%m:%d", [from]) = ?', DateTime.now.strftime("%m:%d"))
    else
      active.repeat("yearly").allDay(allDay_).where('STRFTIME("%m:%d %H:%M", [from]) = ?', DateTime.now.strftime("%m:%d %H:%M"))
    end
  }

  def notify
    EventMailer.event_email(self)
  end

  class << self

    def notify_types
      @@notify_type
    end

    def notify
      [once_, daily_, weekly_, monthly_, yearly_].flatten.compact.each { |event|
        event.notify
      }
    end

    def once_
      events = once(false)
      events = once(true) + events if DateTime.now.strftime("%H:%M").eql?("02:12")
      events
    end

    def daily_
      events = daily(false)
      events = daily(true) + events if DateTime.now.strftime("%H:%M").eql?("09:00")
      events
    end

    def weekly_
      events = weekly(false)
      events = weekly(true) + events if DateTime.now.strftime("%H:%M").eql?("09:00")
      events
    end

    def monthly_
      events = monthly(false)
      events = monthly(true) + events if DateTime.now.strftime("%H:%M").eql?("09:00")
      events
    end

    def yearly_
      events = yearly(false)
      events = yearly(true) + events if DateTime.now.strftime("%H:%M").eql?("09:00")
      events
    end

  end

end

app/models/user.rb
class User < ActiveRecord::Base

  validates :name, :presence => true

  # Include default devise modules. Others available are:
  #:token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me, :confirmed_at

  has_many :events

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  before_filter :authenticate_user!
  before_filter :check_date, :only => [:create, :update]

  def index
    if request.xhr?
      result = current_user.events.map {|event|
        record = {:id => event.id, :title => event.title.to_s, :allDay => event.allDay, :start => event.from, :end => event.to, :repeat => event.repeat || Event.notify_types.first, :className => (event.repeat || Event.notify_types.first).downcase}
      }
      render :json => result.to_json
    end
  end

  def list
    @events = current_user.events
  end

  def create
    event = current_user.events.create(:title => params[:title], :repeat => params[:repeat], :from => @from, :to => @to, :allDay => @allDay)
    render :json => {:id => event.id, :success => true}
  end

  def update
    event = Event.find(params[:id])
    event.update_attributes({:title => params[:title], :repeat => params[:repeat], :from => @from, :to => @to, :allDay => @allDay})
    render :nothing => true
  end

  def destroy
    @event = current_user.events.find(params[:id])
    render :nothing => true and return unless @event
    @event.destroy    
  end

  private

  def check_date
    @allDay = params[:allDay].eql?("true")
    @from = DateTime.strptime(params[:start], "%Y-%m-%d-%H-%M")
    @to = ((params[:allDay].eql?("true") || params[:end].blank?) ? nil : DateTime.strptime(params[:end], "%Y-%m-%d-%H-%M"))
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/destroy.js.erb
$(".event_<%= @event.id %>").remove();

app/views/events/index.html.erb
<div id='wrap'>

  <div id='external-events'>
    <h4>Most Events</h4>
    (<h7>drag & drop</h7>)
    <div class="external-event live-tipsy once" title="Once-off meeting">Meeting</div>
    <div class="external-event live-tipsy daily" title="Daily meeting">Meeting</div>
    <div class="external-event live-tipsy weekly" title="Weekly meeting">Meeting</div>
    <div class="external-event live-tipsy monthly" title="Monthly meeting">Meeting</div>
    <div class="external-event live-tipsy once" title="Once-off 'Out of office'">Out of office</div>
    <div class="external-event live-tipsy daily" title="Daily 'Out of office'">Out of office</div>
    <div class="external-event live-tipsy weekly" title="Weekly 'Out of office'">Out of office</div>
    <div class="external-event live-tipsy monthly" title="Monthly 'Out of office'">Out of office</div>
    <div class="external-event live-tipsy monthly" title="Monthly vocation">Vocation</div>
    <div class="external-event live-tipsy yearly" title="Yearly vocation">Vocation</div>
    <div class="external-event live-tipsyyearly" title="Yearly birthday">Birthday</div>
    <div><%= link_to "My events", list_events_path %></div>
    <div class="">

    </div>
</div>


  <div id='calendar'></div>

  <div id="eventDialog" class="dialog ui-helper-hidden">

    <table>
      <tr>
        <td align="left" style="padding: 5px 0px" ><%= label_tag "Title: " %></td>
        <td align="left" style="padding: 5px 0px"><%= text_field_tag :title %></td>
      </tr>
      <tr>
        <td align="left" style="padding: 5px 0px"><%= label_tag "Repeat: " %></td>
        <td align="left" style="padding: 5px 0px"><%= select_tag(:repeat, options_for_select(Event.notify_types.map { |type| [type, type] }, Event.notify_types.first )) %></td>
      </tr>
    </table>

  </div>

  <div style="clear: both"></div>

</div>

<script type='text/javascript'>

  var event_title = $("#title");
  var event_repeat = $("#repeat");

  $(document).ready(function() {

    function formatted_date(date) {
      if(date){
        return [date.getFullYear(), date.getMonth() + 1, date.getDate(), date.getHours(), date.getMinutes()].join("-")
      } else {
        return ""
      }
    }

    var dialog = $("#eventDialog");
    $(function() {
      dialog.dialog({
        modal: true,
        autoOpen: false,
        width: 400,
        title: "Event",
        close: function(event, ui) {
          event_title.val("");
          event_repeat.val("");
          calendar.fullCalendar( 'rerenderEvents' );
          $(this).dialog( "option" , "event" , null );
          $(this).dialog( "option", "mode", null )
        },
        open: function(event, ui) {
          if($(this).dialog( "option", "mode" )=="new") {
            $(":button:contains('Delete')").attr("disabled","disabled").addClass("ui-state-disabled");
            event_title.val("");
            event_repeat.val("");
          } else {
            $(":button:contains('Delete')").removeAttr("disabled").removeClass("ui-state-disabled");
            event = $(this).dialog( "option", "event" );
            event_title.val(event.title);
            event_repeat.val(event.repeat);
          }
        },
        buttons: [{
          text: "Save",
          click: function() {
            event = $(this).dialog( "option" , "event" );
            event.title = event_title.val();
            event.repeat = event_repeat.val();
            if (event.title) {
              if($(this).dialog( "option", "mode" )=="new") {
                insertEvent(event, function(response){
                  calendar.fullCalendar('renderEvent', $.extend(event, {id: response.id, className: event.repeat.toLowerCase() }), true );
                  dialog.dialog("close");
                });
              } else {
                update( $.extend(event, {className: event.repeat.toLowerCase()}) , function() {
                  dialog.dialog("close");
                })
              }
            }
          }
        }, {
          text: "Delete",
          click: function() {
            event = $(this).dialog( "option" , "event" );
            if(event) {
              remove(event, function() {
                calendar.fullCalendar( 'removeEvents', event.id )
                dialog.dialog("close");
              })
            }
          }
        }, {
          text: "Cancel",
          click: function() {$(this).dialog("close");}
        }]
      });
    });


    /* initialize the external events
    -----------------------------------------------------------------*/

    $('#external-events div.external-event').each(function() {

      // create an Event Object (http://arshaw.com/fullcalendar/docs/event_data/Event_Object/)
      // it doesn't need to have a start or end
      var eventObject = {
        title: $.trim($(this).text()) // use the element's text as the event title
      };

      // store the Event Object in the DOM element so we can get to it later
      $(this).data('eventObject', eventObject);

      // make the event draggable using jQuery UI
      $(this).draggable({
        zIndex: 999,
        revert: true,      // will cause the event to go back to its
        revertDuration: 0  //  original position after the drag
      });

    });


    /* initialize the calendar
    -----------------------------------------------------------------*/

    var calendar = $('#calendar').fullCalendar({
      editable: true,
      selectable: true,
      selectHelper: true,
      droppable: true, // this allows things to be dropped onto the calendar !!!
      header: {
        left: 'prev,next today',
        center: 'title',
        right: 'month,agendaWeek,agendaDay'
      },
      eventClick: function(calEvent, jsEvent, view) {
        dialog.dialog( "option" , "event", calEvent);
        dialog.dialog('open');
      },
      eventDrop: function(event, dayDelta, minuteDelta, allDay, revertFunc) {
        ext = allDay ? {} : {allDay: allDay}
        msg = allDay ? "Event is now all-day" : "Event has a time-of-day"
        alert(msg);
        if (!confirm("Are you sure about this change?")) {
            revertFunc();
          } else {
            update($.extend(event, ext))
          }
        calendar.fullCalendar('unselect');
      },
      eventResize: function(event,dayDelta,minuteDelta,revertFunc) {
        if(!confirm("is this okay?")) {
            revertFunc();
        } else {
          update($.extend(event, {allDay: event.allDay}))
        }
      },
      select: function( startDate, endDate, allDay, jsEvent, view ) {
        dialog.dialog("option", "mode", "new");
        dialog.dialog("option", "event", {start: startDate, end: endDate, allDay: allDay});
        dialog.dialog("open")
      },
      drop: function(date, allDay) { // this function is called when something is dropped
        var _event = $(this)
        // retrieve the dropped element's stored Event Object
        var originalEventObject = _event.data('eventObject');

        // we need to copy it, so that multiple events don't have a reference to the same object
        var copiedEventObject = $.extend({}, originalEventObject);

        // assign it the date that was reported
        copiedEventObject.start = date;
        copiedEventObject.allDay = allDay;

        $.each(["once", "daily", "weekly", "monthly", "yearly"], function(index, item){

          if(_event.hasClass(item)){
            copiedEventObject.repeat = item;
            copiedEventObject.className = item;
          }
        });

        insertEvent(copiedEventObject, function(response){
          // render the event on the calendar
          // the last `true` argument determines if the event "sticks" (http://arshaw.com/fullcalendar/docs/event_rendering/renderEvent/)
          $('#calendar').fullCalendar('renderEvent', $.extend(copiedEventObject, {id: response.id} ), true);
        });

      }

    });

    function insertEvent(eventObject, callback){
      data = {title: eventObject.title, repeat: eventObject.repeat, start: formatted_date(eventObject.start)}
      if(eventObject.end) { data["end"] = formatted_date(eventObject.end)}
      if(eventObject.allDay) { data["allDay"] = eventObject.allDay } else { data["allDay"] = false }
      $.ajax({url: "<%= events_path %>",
        type: 'POST',
        beforeSend: function(xhr) { xhr.setRequestHeader('X-CSRF-Token', $('meta[name="csrf-token"]').attr('content'))},
        data: data,
        success: callback
      })
    }

    function load(){
      $.get("<%= events_path %>").success(function(response){
        $.each(response, function(index, item){
          $('#calendar').fullCalendar('renderEvent', item, true);
        });
      });
    }
    load();

    function update(eventElement, callback){
      data = {"_method": "put", title: eventElement.title, repeat: eventElement.repeat, start: formatted_date(eventElement.start)}
      if(eventElement.end) { data["end"] = formatted_date(eventElement.end) }
      if(eventElement.allDay) { data["allDay"] = eventElement.allDay } else { data["allDay"] = false }
      $.ajax({url: "<%= events_path %>/" + eventElement.id,
        type: 'POST',
        beforeSend: function(xhr) { xhr.setRequestHeader('X-CSRF-Token', $('meta[name="csrf-token"]').attr('content')) },
        data: data,
        success: callback
      })
    }

    function remove(eventElement, callback) {
      $.ajax({url: "<%= events_path %>/" + eventElement.id,
        type: 'POST',
        beforeSend: function(xhr) { xhr.setRequestHeader('X-CSRF-Token', $('meta[name="csrf-token"]').attr('content')) },
        data: {"_method": "delete"},
        success: callback
      })
    }
  });

</script>

app/views/events/index.html.haml
#wrap
  #external-events
    %h4 Most Events
    %h7 (drag & drop)
    .external-event.live-tipsy.once{ :title => "Once-off meeting" } Meeting
    .external-event.live-tipsy.daily{ :title => "Daily meeting" } Meeting
    .external-event.live-tipsy.weekly{ :title => "Weekly meeting" } Meeting
    .external-event.live-tipsy.monthly{ :title => "Monthly meeting" } Meeting
    .external-event.live-tipsy.once{ :title => "Once-off 'Out of office'" } Out of office
    .external-event.live-tipsy.daily{ :title => "Daily 'Out of office'"} Out of office
    .external-event.live-tipsy.weekly{ :title => "Weekly 'Out of office'"} Out of office
    .external-event.live-tipsy.monthly{ :title => "Monthly 'Out of office'"} Out of office
    .external-event.live-tipsy.monthly{ :title => "Monthly vocation" } Vocation
    .external-event.live-tipsy.yearly{ :title => "Yearly vocation" } Vocation
    .external-event.live-tipsy.yearly{ :title => "Yearly birthday" } Birthday
    %div= link_to "My events", list_events_path

  #calendar

  #eventDialog.dialog.ui-helper-hidden
    %table
      %tr
        %td{ :align => "left", :style => "padding: 5px 0px" }
          = label_tag "Title: "
        %td{ :align => "left", :style => "padding: 5px 0px" }
          = text_field_tag :title
      %tr
        %td{ :align => "left", :style => "padding: 5px 0px" }
          = label_tag "Repeat: "
        %td{ :align => "left", :style => "padding: 5px 0px" }
          = select_tag(:repeat, options_for_select(Event.notify_types.map { |type| [type, type.downcase] }, Event.notify_types.first.downcase ))
  %div{ :style => "clear: both" }

:coffeescript
  $(document).ready ->

  event_title = $("#title")
  event_repeat = $("#repeat")

  dialog = $("#eventDialog")

  formatted_date = (date) ->
    if date
      [date.getFullYear(), date.getMonth() + 1, date.getDate(), date.getHours(), date.getMinutes()].join "-"
    else
      ""

  $('#external-events div.external-event').each () ->
    eventObject = {
      title: $.trim $(this).text()
    }

    $(this).data 'eventObject', eventObject

    $(this).draggable
      zIndex: 999
      revert: true
      revertDuration: 0

  insertEvent = (eventObject, callback) ->
    data = {
      title: eventObject.title
      repeat: eventObject.repeat
      start: formatted_date eventObject.start
    }
    if eventObject.end
      data["end"] = formatted_date eventObject.end
    if eventObject.allDay
      data["allDay"] = eventObject.allDay
    else
      data["allDay"] = false
    $.ajax
      url: "#{events_path}"
      type: 'POST'
      beforeSend: (xhr) ->
        xhr.setRequestHeader('X-CSRF-Token', $('meta[name="csrf-token"]').attr('content'))
      data: data
      success: callback

  load = () ->
    $.get("#{events_path}").success (response) ->
      $.each response, (index, item) ->
        $('#calendar').fullCalendar 'renderEvent', item, true

  update = (eventElement, callback) ->
    data = {
      "_method": "put"
      title: eventElement.title
      repeat: eventElement.repeat
      start: formatted_date eventElement.start
    }
    if eventElement.end
      data["end"] = formatted_date eventElement.end
    if eventElement.allDay
      data["allDay"] = eventElement.allDay
    else
      data["allDay"] = false
    $.ajax
      url: "#{events_path}/" + eventElement.id
      type: 'POST'
      beforeSend: (xhr) ->
        xhr.setRequestHeader('X-CSRF-Token', $('meta[name="csrf-token"]').attr('content'))
      data: data
      success: callback

  remove = (eventElement, callback) ->
    $.ajax
      url: "#{events_path}/" + eventElement.id
      type: 'POST'
      beforeSend: (xhr) ->
        xhr.setRequestHeader('X-CSRF-Token', $('meta[name="csrf-token"]').attr('content'))
      data: {"_method": "delete"}
      success: callback

  calendar = $('#calendar').fullCalendar
    editable: true,
    selectable: true,
    selectHelper: true,
    droppable: true,
    header:
      left: 'prev,next today'
      center: 'title'
      right: 'month,agendaWeek,agendaDay'
    eventClick: (calEvent, jsEvent, view) ->
      dialog.dialog "option", "event", calEvent
      dialog.dialog 'open'
    eventDrop: (event, dayDelta, minuteDelta, allDay, revertFunc) ->
      ext = if allDay then {} else {allDay: allDay}
      msg = if allDay then "Event is now all-day" else "Event has a time-of-day"
      alert(msg)
      if (!confirm("Are you sure about this change?"))
        revertFunc()
      else
        update $.extend(event, ext)
      calendar.fullCalendar 'unselect'
    eventResize: (event,dayDelta,minuteDelta,revertFunc) ->
      if(!confirm("is this okay?"))
        revertFunc()
      else
        update $.extend(event, {allDay: event.allDay})
    select: ( startDate, endDate, allDay, jsEvent, view ) ->
      dialog.dialog "option", "mode", "new"
      dialog.dialog "option", "event", {start: startDate, end: endDate, allDay: allDay}
      dialog.dialog "open"
    drop: (date, allDay) ->
      _event = $(this)
      originalEventObject = _event.data 'eventObject'
      copiedEventObject = $.extend {}, originalEventObject
      copiedEventObject.start = date
      copiedEventObject.allDay = allDay
      $.each ["once", "daily", "weekly", "monthly", "yearly"], (index, item) ->
        if _event.hasClass item
          copiedEventObject.repeat = item
          copiedEventObject.className = item

      insertEvent copiedEventObject, (response) ->
        $('#calendar').fullCalendar('renderEvent', $.extend(copiedEventObject, {id: response.id} ), true)

  dialog.dialog
    modal: true
    autoOpen: false
    width: 400
    title: "Event"
    close: (event, ui) ->
      event_title.val ""
      event_repeat.val ""
      calendar.fullCalendar 'rerenderEvents'
      $(this).dialog "option" , "event" , null
      $(this).dialog "option", "mode", null
    open: (event, ui) ->
      if $(this).dialog("option", "mode") == "new"
        $(":button:contains('Delete')").attr("disabled","disabled").addClass "ui-state-disabled"
        event_title.val ""
        event_repeat.val ""
      else
        $(":button:contains('Delete')").removeAttr("disabled").removeClass "ui-state-disabled"
        event = $(this).dialog "option", "event"
        event_title.val event.title
        event_repeat.val event.repeat
    buttons: [
      {
        text: "Save"
        click: () ->
          event = $(this).dialog "option", "event"
          event.title = event_title.val()
          event.repeat = event_repeat.val()
          if event.title
            if $(this).dialog("option", "mode" ) == "new"
              insertEvent event, (response) ->
                calendar.fullCalendar('renderEvent', $.extend(event, {id: response.id, className: event.repeat.toLowerCase() }), true)
                dialog.dialog "close"
            else
              update( $.extend(event, {className: event.repeat.toLowerCase()}) , () ->
                dialog.dialog "close"
              )
      }
      {
        text: "Delete"
        click: () ->
          event = $(this).dialog "option" , "event"
          if event
            remove event, () ->
              calendar.fullCalendar 'removeEvents', event.id
              dialog.dialog "close"
      }
      {
        text: "Cancel"
        click: () ->
          $(this).dialog "close"
      }
    ]

  load()
  $('.live-tipsy').tipsy {live: true, gravity: 'w'}

app/views/events/list.html.haml
#event-list
  #wrap
    #external-events
      .external-event
        = link_to "My Calendar", events_path   
    .ui-widget{ :style => "float: left; padding-left: 20px" }
      %table.ui-widget.ui-widget-content
        %thead
          %tr.ui-widget-header
            %th Title
            %th Repeat
            %th Start
            %th End
            %th Control
        %tbody
          - @events.each do |event|
            %tr{ :class => "event_#{event.id} #{(event.repeat || Event.notify_types.first).downcase}" }
              %td= event.title
              %td= event.repeat
              %td= event.from.strftime("%Y-%m-%d %H:%M")
              %td= event.to.blank? ? "" : event.to.strftime("%Y-%m-%d %H:%M")
              %td= link_to "Delete", event_path(event), :id => event.id, :class => "event"          
          
:coffeescript
  $('#event-list .event').click (eventElement) ->
    if confirm "Are you sure?"
      $.ajax {
        url: #{events_path}/ + this.id
        type: 'POST'
        beforeSend: 
          (xhr) ->
            xhr.setRequestHeader 'X-CSRF-Token', ($('meta[name="csrf-token"]').attr 'content')
        data: 
          "_method": "delete"      
      }
    return false;

app/views/layouts/_user_nav.html.haml
#user_nav
  - if user_signed_in?
    Signed in as 
    = link_to current_user.name, edit_user_registration_path(current_user)
    |
    = link_to "Sign out", destroy_user_session_path, :method => :delete
  - else
    = link_to "Sign up", new_user_registration_path 
    or 
    = link_to "sign in", new_user_session_path

%p.notice= notice
%p.alert= alert

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Ievent
    = stylesheet_link_tag "application"
    = stylesheet_link_tag "fullcalendar-1.5.3/fullcalendar/fullcalendar.print.css", :media => "print"
    
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    = render "layouts/user_nav"
    = yield      

app/views/users/_links.haml
- if controller_name != 'sessions'
  = link_to "Sign in", new_session_path(resource_name)
  %br


- if devise_mapping.registerable? && controller_name != 'registrations'
  = link_to "Sign up", new_registration_path(resource_name)
  %br

- if devise_mapping.recoverable? && controller_name != 'passwords'
  <%= link_to "Forgot your password?", new_password_path(resource_name)
  %br

- if devise_mapping.confirmable? && controller_name != 'confirmations'
  = link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name)
  %br

- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks'
  = link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name)
  %br

- if devise_mapping.omniauthable?
  - resource_class.omniauth_providers.each do |provider|
    = link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider)
    %br